Merge Cellpose In To Main
nygctech/hudson pull request #36
Opened 2024-10-23 18:31 UTC by SRodwin

2024-10-25 17:53 UTC, krpandit commented on config/config.yaml
> -output_directory: /gpfs/commons/groups/nygcfaculty/PySeq/20210323_4i4color/pipeline
We should sanitize this path name and make  it a generic name in user home directory

2024-10-25 18:01 UTC, krpandit commented on workflow/.tests/unit/common.py
should change 
config_path = '/nethome/kpandit/hudson/workflow/.tests/unit/pytest_config.yaml'
to 
config_path = Path(os.abspath(__file__)).parent / 'pytest_config.yaml'

2024-10-25 18:04 UTC, krpandit commented on workflow/.tests/unit/test_segmentation.py
use test config path fixture for --configfile argument

2024-10-25 18:04 UTC, krpandit commented on workflow/.tests/unit/test_spatial_neighborhood.py
use test config path fixture for --configfile argument

2024-10-25 18:17 UTC, krpandit requested changes
I put in a few minor comments to change. I also tried running the tests but I got this error below before any tests could actually run. Any ideas why? The tests shouldn't import pytorch, but it should submit a job which does. 


E   ImportError: Failed to load PyTorch C extensions:
E       It appears that PyTorch has loaded the `torch/_C` folder
E       of the PyTorch repository rather than the C extensions which
E       are expected in the `torch._C` namespace. This can occur when
E       using the `install` workflow. e.g.
E           $ python setup.py install && python -c "import torch"
E   
E       This error can generally be solved using the `develop` workflow
E           $ python setup.py develop && python -c "import torch"  # This should succeed
E       or by running Python from a different directory.

2024-10-29 20:06 UTC, SRodwin commented on workflow/.tests/unit/test_spatial_neighborhood.py
we no longer run spatial neighborhood

2024-10-31 21:28 UTC, merged